-- ═══════════════════════════════════════════════════════════
-- kdt-ai (kdt-ai.dreamitbiz.com) 전용 테이블 셋업 — kdt_ 접두사
-- skala_ 와 분리 운영(2026-07-21 대표 확정). 접속 프로젝트는 공용(단일 org).
-- Supabase SQL Editor에서 이 파일 하나만 실행하면 kdt-ai 회원·게시판·평가가 활성화된다.
-- 개별 파일(schema.sql / 2026-07-14_profiles / 2026-07-15_* / 2026-07-21_title)도
-- kdt_ 로 치환돼 있으니 참고. 아래는 그 통합본.
-- ═══════════════════════════════════════════════════════════

-- ── 관리자 판별 함수 ──
create or replace function public.kdt_is_admin() returns boolean
language sql stable as $$
  select coalesce(
    (auth.jwt() ->> 'email') in (
      'aebon@kyonggi.ac.kr', 'aebon@kakao.com', 'boraborami@gmail.com', 'humanaiphd@gmail.com'
    ), false);
$$;

-- ── 회원 프로필 ──
create table if not exists public.kdt_profiles (
  user_id     uuid primary key references auth.users(id) on delete cascade,
  name        text,
  email       text,
  role        text not null default 'student' check (role in ('student', 'instructor')),
  title       text check (title is null or title in ('chief_manager','class_manager','lead_professor','practice_professor')),
  track       text,
  class_no    int,
  teach_classes jsonb default '[]'::jsonb,
  confirmed_at  timestamptz,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);
alter table public.kdt_profiles enable row level security;
drop policy if exists "kdt_profiles_self_select" on public.kdt_profiles;
create policy "kdt_profiles_self_select" on public.kdt_profiles for select using (auth.uid() = user_id or public.kdt_is_admin());
drop policy if exists "kdt_profiles_self_insert" on public.kdt_profiles;
create policy "kdt_profiles_self_insert" on public.kdt_profiles for insert with check (auth.uid() = user_id);
drop policy if exists "kdt_profiles_self_update" on public.kdt_profiles;
create policy "kdt_profiles_self_update" on public.kdt_profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ── 게시판(공지·Q&A) ──
create table if not exists public.kdt_posts (
  id         bigint generated by default as identity primary key,
  type       text not null default 'qna' check (type in ('qna','notice')),
  title      text not null,
  body       text,
  author_id  uuid references auth.users(id) on delete set null,
  author_name text,
  is_pinned  boolean default false,
  created_at timestamptz default now()
);
create index if not exists kdt_posts_type on public.kdt_posts(type, created_at desc);
alter table public.kdt_posts enable row level security;
drop policy if exists "kdt_posts_read" on public.kdt_posts;
create policy "kdt_posts_read" on public.kdt_posts for select using (true);
drop policy if exists "kdt_posts_write" on public.kdt_posts;
create policy "kdt_posts_write" on public.kdt_posts for insert with check (auth.uid() = author_id);
drop policy if exists "kdt_posts_admin" on public.kdt_posts;
create policy "kdt_posts_admin" on public.kdt_posts for all using (public.kdt_is_admin()) with check (public.kdt_is_admin());

-- ── 댓글 ──
create table if not exists public.kdt_comments (
  id         bigint generated by default as identity primary key,
  post_id    bigint references public.kdt_posts(id) on delete cascade,
  body       text not null,
  author_id  uuid references auth.users(id) on delete set null,
  author_name text,
  created_at timestamptz default now()
);
create index if not exists kdt_comments_post on public.kdt_comments(post_id, created_at);
alter table public.kdt_comments enable row level security;
drop policy if exists "kdt_comments_read" on public.kdt_comments;
create policy "kdt_comments_read" on public.kdt_comments for select using (true);
drop policy if exists "kdt_comments_write" on public.kdt_comments;
create policy "kdt_comments_write" on public.kdt_comments for insert with check (auth.uid() = author_id);

-- ── 학습 진도 ──
create table if not exists public.kdt_progress (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  completed  jsonb default '[]'::jsonb,
  user_name  text,
  updated_at timestamptz default now()
);
alter table public.kdt_progress enable row level security;
drop policy if exists "kdt_progress_self" on public.kdt_progress;
create policy "kdt_progress_self" on public.kdt_progress for all using (auth.uid() = user_id or public.kdt_is_admin()) with check (auth.uid() = user_id);

-- ── 종합실습 평가 기록(관리자 전용) ──
create table if not exists public.kdt_evaluations (
  id           uuid primary key default gen_random_uuid(),
  subject_id   text not null,
  student_name text not null,
  student_no   text default '',
  track        text,
  class_no     int,
  profile_id   uuid,
  scores       jsonb not null default '{}'::jsonb,
  note_basis   text default '',
  note_improve text default '',
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists kdt_evaluations_subject_idx on public.kdt_evaluations(subject_id, track, class_no);
alter table public.kdt_evaluations enable row level security;
drop policy if exists "kdt_evaluations_admin_all" on public.kdt_evaluations;
create policy "kdt_evaluations_admin_all" on public.kdt_evaluations for all using (public.kdt_is_admin()) with check (public.kdt_is_admin());
